# Generated by Django 6.1 on 2026-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='hardware_spec',
            field=models.CharField(default='RTX 4070 | i7-13700K | 32GB', max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='zone',
            field=models.CharField(default='Standard Arena', max_length=50),
        ),
    ]
