# Generated by Django 6.1 on 2026-08-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_computer_hardware_spec_computer_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='zone',
            field=models.CharField(default='Standard Zone', max_length=50),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=12000.0, max_digits=12),
        ),
    ]
