# Generated by Django 6.1 on 2026-08-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_computer_zone_alter_tariff_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='is_open_time',
            field=models.BooleanField(default=False, help_text='True if open-ended session without fixed timer'),
        ),
        migrations.AddField(
            model_name='session',
            name='is_open_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='computer',
            name='time_remaining',
            field=models.IntegerField(default=0, help_text='Remaining or elapsed seconds'),
        ),
    ]
