# Generated by Django 6.1 on 2026-08-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_category_order_product_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik')], default='CASH', max_length=10)),
                ('category', models.CharField(default='Boshqa', max_length=100)),
                ('recipient_name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik')], default='CASH', max_length=10),
        ),
    ]
