# Generated by Django 6.1 on 2026-08-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_expense_order_payment_method_session_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cover_path', models.CharField(help_text='Cover banner image URL or local file path', max_length=500)),
                ('executable_path', models.CharField(help_text='Executable file path or launch command', max_length=500)),
                ('category', models.CharField(choices=[('FPS', 'FPS / Shooter'), ('Action', 'Action / Adventure'), ('Sports', 'Sports / Racing'), ('Strategy', 'Strategy / MOBA')], default='FPS', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bar_orders', to='billing.computer'),
        ),
    ]
