# Generated by Django 6.1 on 2026-08-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_product_cost_price_alter_product_price_stocksupply'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='working_directory',
            field=models.CharField(blank=True, help_text='Working directory path for executable', max_length=500, null=True),
        ),
    ]
