# Generated by Django 6.1 on 2026-08-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_game_working_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='session',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='session',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='stocksupply',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)')], default='CASH', max_length=10),
        ),
    ]
