# Generated by Django 6.1 on 2026-08-12 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_order_card_amount_order_cash_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Masalan: 1.0.1', max_length=30, unique=True)),
                ('zip_file', models.FileField(help_text="client/ papkasining zip arxivi (config.json'siz)", upload_to='client_builds/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Faqat True bo'lgan eng so'nggi versiya kiosklarga taqdim etiladi")),
                ('released_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bonus_points', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Tizimga kirdi'), ('SESSION_STOPPED', 'Seans yakunlandi'), ('EMERGENCY_LOCK', 'Favqulodda bloklandi'), ('TARIFF_CHANGED', "Tarif narxi o'zgartirildi"), ('ORDER_APPROVED', 'Buyurtma tasdiqlandi'), ('ORDER_DELIVERED', 'Buyurtma yetkazildi'), ('ORDER_CANCELLED', 'Buyurtma bekor qilindi'), ('CUSTOMER_TOPUP', "Mijoz balansi to'ldirildi"), ('CUSTOMER_SPEND', 'Mijoz balansidan yechildi'), ('EXPENSE_CREATED', "Rasxod qo'shildi"), ('STOCK_SUPPLY', 'Tovar kirim qilindi'), ('OTHER', 'Boshqa')], default='OTHER', max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='billing.customer'),
        ),
        migrations.AddField(
            model_name='session',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='billing.customer'),
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TOPUP', "To'ldirish"), ('SPEND', 'Sarflash'), ('ADJUST', 'Tuzatish')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
