# Generated by Django 6.1 on 2026-08-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_clientbuild_customer_auditlog_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Tizimga kirdi'), ('SESSION_STOPPED', 'Seans yakunlandi'), ('EMERGENCY_LOCK', 'Favqulodda bloklandi'), ('TARIFF_CHANGED', "Tarif narxi o'zgartirildi"), ('ORDER_APPROVED', 'Buyurtma tasdiqlandi'), ('ORDER_DELIVERED', 'Buyurtma yetkazildi'), ('ORDER_CANCELLED', 'Buyurtma bekor qilindi'), ('CUSTOMER_TOPUP', "Mijoz balansi to'ldirildi"), ('CUSTOMER_SPEND', 'Mijoz balansidan yechildi'), ('CUSTOMER_LOGIN', 'Mijoz kiosk orqali tizimga kirdi'), ('CUSTOMER_PASSWORD_RESET', 'Mijoz paroli tozalandi'), ('EXPENSE_CREATED', "Rasxod qo'shildi"), ('STOCK_SUPPLY', 'Tovar kirim qilindi'), ('OTHER', 'Boshqa')], default='OTHER', max_length=30),
        ),
    ]
