# Generated by Django 6.1 on 2026-08-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_customer_password_hash_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='balance_deducted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)'), ('BALANCE', 'Mijoz balansi')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)'), ('BALANCE', 'Mijoz balansi')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)'), ('BALANCE', 'Mijoz balansi')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='stocksupply',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)'), ('BALANCE', 'Mijoz balansi')], default='CASH', max_length=10),
        ),
    ]
