# Generated by Django 6.1 on 2026-08-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_session_balance_deducted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Tizimga kirdi'), ('SESSION_STOPPED', 'Seans yakunlandi'), ('EMERGENCY_LOCK', 'Favqulodda bloklandi'), ('TARIFF_CHANGED', "Tarif narxi o'zgartirildi"), ('ORDER_APPROVED', 'Buyurtma tasdiqlandi'), ('ORDER_DELIVERED', 'Buyurtma yetkazildi'), ('ORDER_CANCELLED', 'Buyurtma bekor qilindi'), ('CUSTOMER_TOPUP', "Mijoz balansi to'ldirildi"), ('CUSTOMER_SPEND', 'Mijoz balansidan yechildi'), ('CUSTOMER_LOGIN', 'Mijoz kiosk orqali tizimga kirdi'), ('CUSTOMER_PASSWORD_RESET', 'Mijoz paroli tozalandi'), ('EXPENSE_CREATED', "Rasxod qo'shildi"), ('STOCK_SUPPLY', 'Tovar kirim qilindi'), ('REMOTE_SHUTDOWN', "Kompyuter uzoqdan o'chirildi"), ('FORCE_CLOSE_APP', 'Dastur majburan yopildi'), ('OTHER', 'Boshqa')], default='OTHER', max_length=30),
        ),
    ]
