# Generated by Django 6.1 on 2026-08-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lifetime_balance_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
