# Generated by Django 6.1 on 2026-08-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_customer_lifetime_balance_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)'), ('BALANCE', 'Mijoz balansi')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='type',
            field=models.CharField(choices=[('TOPUP', "To'ldirish"), ('SPEND', 'Sarflash'), ('ADJUST', 'Tuzatish'), ('BONUS', "To'ldirish bonusi")], max_length=10),
        ),
    ]
