# Generated by Django 6.1 on 2026-08-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_customertransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)'), ('BALANCE', 'Mijoz balansi'), ('FREE', 'Bepul (Comp)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)'), ('BALANCE', 'Mijoz balansi'), ('FREE', 'Bepul (Comp)')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)'), ('BALANCE', 'Mijoz balansi'), ('FREE', 'Bepul (Comp)')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)'), ('BALANCE', 'Mijoz balansi'), ('FREE', 'Bepul (Comp)')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='stocksupply',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik'), ('SPLIT', 'Aralash (Naqd + Card)'), ('BALANCE', 'Mijoz balansi'), ('FREE', 'Bepul (Comp)')], default='CASH', max_length=10),
        ),
    ]
