# Generated by Django 6.1 on 2026-08-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_customertransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_order_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
