# Generated by Django 6.1 on 2026-08-15 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_order_client_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePathOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executable_path', models.CharField(max_length=500)),
                ('working_directory', models.CharField(blank=True, max_length=500, null=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_path_overrides', to='billing.computer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_overrides', to='billing.game')),
            ],
            options={
                'unique_together': {('game', 'computer')},
            },
        ),
    ]
