# Generated by Django 6.1 on 2026-08-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_gamepathoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_path',
            field=models.CharField(blank=True, default='', help_text='Cover banner image URL or local file path', max_length=500),
        ),
    ]
