# Generated by Django 6.1 on 2026-08-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_alter_game_cover_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksupply',
            name='client_order_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
